version: '3.8'

services:
  #============================================================================================
  #DB
  database:
    build: 
      context: ./db    
      dockerfile: Dockerfile
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=tienda_perritos
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno123
    volumes:
      # ¡Crucial para tu evaluación! Persistencia de datos.
      - db-data:/var/lib/mysql 
    networks:
      - app-network
  #============================================================================================
  #back
  backend:
    build:
      context: ./backend     
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=database      
      - DB_USER=alumno
      - DB_PASSWORD=alumno123
      - DB_NAME=tienda_perritos
      - PORT=3001
    depends_on:
      
      - database              
    networks:
      - app-network

  # ============================================================================================
  # Front
 
  frontend:
    build:
      context: ./frontend     
      dockerfile: Dockerfile
    container_name: nginx-frontend
    ports:
      - "8080:80"             
    depends_on:

      - backend               
    networks:
      - app-network


volumes:
  db-data:
   

networks:
  app-network:
    
    driver: bridge